nodes:
  enron_source_mongo:
    type: mongodb
    uri: mongodb://${MONGODB_ENRON_SOURCE_USER}:${MONGODB_ENRON_SOURCE_PASSWORD}@${MONGODB_ENRON_SOURCE_URI}/enron
    tail: false
  enron_sink_mongo:
    type: mongodb
    uri: mongodb://${MONGODB_ENRON_SINK_USER}:${MONGODB_ENRON_SINK_PASSWORD}@${MONGODB_ENRON_SINK_URI}/enron
    ssl: true
    bulk: true
    wc: 2
    fsync: true
  enron_sink_es:
    type: elasticsearch
    uri: https://${ES_ENRON_SINK_USER}:${ES_ENRON_SINK_PASSWORD}@${ES_ENRON_SINK_URI}
  enron_source_rethink:
    type: rethinkdb
    uri: rethink://admin:${RETHINKDB_ENRON_SOURCE_PASSWORD}@${RETHINKDB_ENRON_SOURCE_URI}/enron
    ssl: true
  enron_sink_rethink:
    type: rethinkdb
    uri: rethink://admin:${RETHINKDB_ENRON_SINK_PASSWORD}@${RETHINKDB_ENRON_SINK_URI}/enron
    ssl: true
  enron_sink_postgres:
    type: postgres
    uri: postgres://${POSTGRES_ENRON_SINK_USER}:${POSTGRES_ENRON_SINK_PASSWORD}@${POSTGRES_ENRON_SINK_URI}
